before_script:

stages:
  - build
  - run
  - package

build-linux:
  stage: build
  tags:
    - centos8 python3
  only:
    - master
  script:
    - mkdir -p bin/linux

    - pip install redis
    - pip install requests
    - pip install elementpath

    - pyinstaller -F bundleAssets.py
    - dist/bundleAssets -h
    - cp dist/bundleAssets bin/linux/bundleAssets
    
    - pyinstaller -F updateBundle.py
    - dist/updateBundle -h
    - cp dist/updateBundle bin/linux/updateBundle
  artifacts:
    name: linux
    paths:
      - bin/linux
  when: delayed
  start_in: 1 seconds

build-mac:
  stage: build
  tags:
    - mac python3
  only:
    - master
  script:
    - mkdir -p bin/mac

    - pip install redis
    - pip install requests
    - pip install elementpath

    - pyinstaller -F bundleAssets.py
    - dist/bundleAssets -h
    - cp dist/bundleAssets bin/mac/bundleAssets
    
    - pyinstaller -F updateBundle.py
    - dist/updateBundle -h
    - cp dist/updateBundle bin/mac/updateBundle
  artifacts:
    name: mac
    paths:
      - bin/mac
  when: delayed
  start_in: 1 seconds

build-windows:
  stage: build
  tags:
    - windows10 python3
  only:
    - master
  script:
    - mkdir -p bin/windows

    - pip install redis
    - pip install requests
    - pip install elementpath

    - pyinstaller -F bundleAssets.py
    - dist/bundleAssets.exe -h
    - cp dist/bundleAssets.exe bin/windows/bundleAssets.exe
    
    - pyinstaller -F updateBundle.py
    - dist/updateBundle.exe -h
    - cp dist/updateBundle.exe bin/windows/updateBundle.exe
  artifacts:
    name: windows
    paths:
      - bin/windows
  when: delayed
  start_in: 1 seconds

run-Android-updateBundle:
  stage: run
  tags:
    - zy
  only:
    - master
  needs: ["build-windows"]
  script:
    - mkdir -p out/updateBundleAndroid
    - ./bin/windows/updateBundle.exe -B 1141685 -I ./data/ua690292 -O ./out/updateBundleAndroid
  artifacts:
    name: updateBundleOutAndroid
    paths:
      - out/updateBundleAndroid

run-iOS-updateBundle:
  stage: run
  tags:
    - zy
  only:
    - master
  needs: ["build-windows"]
  script:
    - mkdir -p out/updateBundleiOS
    - ./bin/windows/updateBundle.exe -B 1141715 -I ./data/ui690319 -O ./out/updateBundleiOS
  artifacts:
    name: updateBundleOutiOS
    paths:
      - out/updateBundleiOS

run-Android-bundleAssets:
  stage: run
  tags:
    - zy
  only:
    - master
  needs: ["build-windows"]
  script:
    - mkdir -p out/bundleAssetsAndroid
    - ./bin/windows/bundleAssets.exe -B 1141451	 -I ./data/fa690135 -O ./out/bundleAssetsAndroid
  artifacts:
    name: bundleAssetsOutAndroid
    paths:
      - out/bundleAssetsAndroid

run-iOS-bundleAssets:
  stage: run
  tags:
    - zy
  only:
    - master
  needs: ["build-windows"]
  script:
    - mkdir -p out/bundleAssetsiOS
    - ./bin/windows/bundleAssets.exe -B 1141360	 -I ./data/fi690100 -O ./out/bundleAssetsiOS
  artifacts:
    name: bundleAssetsOutiOS
    paths:
      - out/bundleAssetsiOS

package-bin:
  stage: package
  tags:
    - centos8 python3
  only:
    - master
  needs: ["build-linux", "build-mac", "build-windows"]
  script:
    - ls bin
  artifacts:
    name: all
    paths:
      - bin

package-out:
  stage: package
  tags:
    - centos8 python3
  only:
    - master
  needs: ["run-Android-updateBundle", "run-iOS-updateBundle", "run-Android-bundleAssets", "run-iOS-bundleAssets"]
  script:
    - ls out
  artifacts:
    name: all-out
    paths:
      - out


