before_script:
  - source ~/.bashrc

stages:
  - build

build-mac:
  stage: build
  tags:
    - python mac
  only:
    - master
  script:
    - mkdir -p bin/mac

    - pyinstaller -F bundleAssets.py -p /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
    - dist/bundleAssets -h
    - cp dist/bundleAssets bin/mac/bundleAssets
    
    - pyinstaller -F updateBundle.py -p /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
    - dist/updateBundle -h
    - cp dist/updateBundle bin/mac/updateBundle
  artifacts:
    paths:
      - bin

