before_script:

stages:
  - build
  - package
  - run

build-linux:
  stage: build
  tags:
    - centos8 python3
  only:
    - master
  script:
    - mkdir -p bin/linux

    - pip install redis
    - pip install requests
    - pip install elementpath

    - pyinstaller -F bundleAssets.py
    - dist/bundleAssets -h
    - cp dist/bundleAssets bin/linux/bundleAssets
    
    - pyinstaller -F updateBundle.py
    - dist/updateBundle -h
    - cp dist/updateBundle bin/linux/updateBundle
  artifacts:
    name: linux
    paths:
      - bin/linux

build-mac:
  stage: build
  tags:
    - python mac
  only:
    - master
  script:
    - source ~/.bashrc
    - mkdir -p bin/mac

    - pyinstaller -F bundleAssets.py -p /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
    - dist/bundleAssets -h
    - cp dist/bundleAssets bin/mac/bundleAssets
    
    - pyinstaller -F updateBundle.py -p /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
    - dist/updateBundle -h
    - cp dist/updateBundle bin/mac/updateBundle
  artifacts:
    name: mac
    paths:
      - bin/mac

build-windows:
  stage: build
  tags:
    - python windows
  only:
    - master
  script:
    - mkdir -p bin/windows

    - pyinstaller -F bundleAssets.py -p E:\NewPackageAnalysize\venv\Lib\site-packages
    - dist/bundleAssets.exe -h
    - cp dist/bundleAssets.exe bin/windows/bundleAssets.exe
    
    - pyinstaller -F updateBundle.py -p E:\NewPackageAnalysize\venv\Lib\site-packages
    - dist/updateBundle.exe -h
    - cp dist/updateBundle.exe bin/windows/updateBundle.exe
  artifacts:
    name: windows
    paths:
      - bin/windows

package:
  stage: package
  tags:
    - centos8 python3
  only:
    - master
  needs: ["build-linux", "build-mac", "build-windows"]
  script:
    - ls bin
  artifacts:
    name: all
    paths:
      - bin

run-updateBundle:
  stage: run
  tags:
    - python windows
  only:
    - master
  needs: ["build-windows"]
  script:
    - mkdir -p out/updateBundle
    - ./bin/windows/updateBundle.exe -B 1139362 -I ./data/u688923 -O ./out/updateBundle
  artifacts:
    name: updateBundleOut
    paths:
      - out/updateBundle

run-bundleAssets:
  stage: run
  tags:
    - python windows
  only:
    - master
  needs: ["build-windows"]
  script:
    - mkdir -p out/bundleAssets
    - ./bin/windows/bundleAssets.exe -B 1139144 -I ./data/f688822 -O ./out/bundleAssets
  artifacts:
    name: bundleAssetsOut
    paths:
      - out/bundleAssets
